### ISSUE TITLE
rename file error

### ISSUE THREAD

**Issue by jkay89** [skuroda/Sublime-AdvancedNewFile#125]
Error code quoted:

> Traceback (most recent call last):
File "advanced_new_file.commands.command_base in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 306, in on_done
File "advanced_new_file.commands.command_base in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 333, in entered_filename
File "advanced_new_file.commands.move_file_command in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 47, in entered_file_action
File "advanced_new_file.commands.move_file_command in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 62, in _rename_file
File "advanced_new_file.commands.move_file_command in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 69, in move_from_argument
File "advanced_new_file.commands.command_base in C:\Users\Enders\AppData\Roaming\Sublime Text 3\Installed Packages\AdvancedNewFile.sublime-package", line 428, in _find_open_file
File "C:\Program Files\Sublime Text 3\sublime.py", line 227, in find_open_file
view_id = sublime_api.window_find_open_file(self.window_id, fname)
TypeError: String required

User settings quoted:

> {
    "alias": {},
    // false by default
    "auto_refresh_sidebar": false,
    "file_templates": {},
    "rename_file_default_root": "current",
    "copy_file_default_root": "current",
    "shell_input": true,
}

User keybindings quoted:

> [
	{ "keys": ["ctrl+shift+n"], "command": "advanced_new_file_move", "args": {"rename_file": true}}
]

What I typed into the ANF console thingy quoted:

> file.html

what I expected to happen:

I have a project folder named **New Folder** with a subfolder of **1**, within the **1** folder, I have a file called **file** with no extension, I'd been having issues with the rename command, so I made a test environment to experiment with. I tried to rename **file** to **file.html** and it did nothing but did produce the above error. I hope I have provided all information you may need, if not, please tell me what else I need to give you and I'll do my best.

**Comment by skuroda** [comment]
Hi Jackie, thanks for the thorough definition of the problem. I see from the key binding you have a set of arguments. For a key binding, that is actually unnecessary. That set of arguments was so I could reuse the same command to handle moves from the side bar. Now that I've worked a bit more with the ST (and python) I'd probably restructure it, but it's a pretty low priority for me at the moment.

So with all that being said, please try removing the argument from the key binding and try to rename the file again.

**Comment by jkay89** [comment]
Ah, thank you, that did indeed resolve the issue, and I've seen enough bad issue posts to realize that half the trouble with helping people is the fact they don't give enough information. It's like playing 20 questions with them only you're asking more around 50 million just to get a straight answer.

**Comment by skuroda** [comment]
That is an excellent way to describe tickets that come in.  Anyways,  glad we were able to resolve the issue.  Thanks for using advanced new file.
