### ISSUE TITLE
file template not work

### ISSUE THREAD

**Issue by gatspy** [skuroda/Sublime-AdvancedNewFile#151]
{
    "shell_input":true,
    "file_templates": {
        "js": [
            "Packages/User/MyTmpl/js.sublime-snippet"
        ],
        "py": [
            "Packages/User/MyTmpl/python.sublime-snippet"
        ]
    }
}

create  new file by ⌥ +⌘+N, not use snippet.

**Comment by skuroda** [comment]
Are there any errors in the ST console? Can you provide the snippet as well as the input file path you used.

**Comment by gatspy** [comment]
add new file. console without any error message .
python.sublime-snippet:
<snippet>
    <content><![CDATA[
#!/usr/bin/python
# -*- coding: utf-8 -*-


]]></content>
    <description>Python File Template</description>
    <tabTrigger>pyf</tabTrigger>
</snippet>

**Comment by gatspy** [comment]
delete current file from command palette, console display the following error message.
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "advanced_new_file.commands.delete_file_command in /Users/Gatspy/Library/Application Support/Sublime Text 3/Installed Packages/AdvancedNewFile.sublime-package", line 18, in run
  File "advanced_new_file.commands.delete_file_command in /Users/Gatspy/Library/Application Support/Sublime Text 3/Installed Packages/AdvancedNewFile.sublime-package", line 44, in _delete_current_file
  File "advanced_new_file.commands.delete_file_command in /Users/Gatspy/Library/Application Support/Sublime Text 3/Installed Packages/AdvancedNewFile.sublime-package", line 64, in _delete_file
  File "advanced_new_file.commands.delete_file_command in /Users/Gatspy/Library/Application Support/Sublime Text 3/Installed Packages/AdvancedNewFile.sublime-package", line 71, in _execute_delete_file
  File "send2trash.plat_osx in /Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package", line 44, in send2trash
  File "send2trash.plat_osx in /Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package", line 33, in check_op_result
OSError: permissions error (on file open)
```
