### ISSUE TITLE
FileHeader is very slow

### ISSUE THREAD

**Issue by fate-lovely** [skuroda/Sublime-AdvancedNewFile#164]
![file-header-slow](https://cloud.githubusercontent.com/assets/4210829/23391382/d56fb6aa-fdaf-11e6-8554-80fdb4e86055.gif)
It takes too much time to add header info.
OS: macOS Sierra
Memory: 16G
CPU: 2.2 GHz Intel Core i7 

Below is the console log.
```text
reloading settings Packages/FileHeader/FileHeader.sublime-settings
reloading plugin FileHeader.FileHeader
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 168, in reload_plugin
    el.on_activated(v)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 685, in on_activated
    block(view, self.update_automatically, view, FILE_PATH)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 339, in block
    _block()
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 337, in _block
    callback(*args, **kwargs)
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 594, in update_automatically
    syntax_type = get_syntax_type(view.file_name())
  File "/Users/cj/Library/Application Support/Sublime Text 3/Packages/FileHeader/FileHeader.py", line 298, in get_syntax_type
    if suffix in extension_equivalence:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by fate-lovely** [comment]
I am sorry to post in the wrong place.
